# Generated by Django 3.2.7 on 2021-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='indore', max_length=255),
            preserve_default=False,
        ),
    ]
